export const user1 = {
  firstName: "Jane",
  lastName: "Smith",
  city: "San Francisco",
  state: "CA",
  desiredPosition: "Data Scientist",
  dreamJob: "Amazon",
  email: "janesmith23@gmail.com",
  password: "$2b$16$SQ7VGLeQeilyzD.5lBpPAeYbILH4.6JKWCTkF/Sw/s95PVqbTEd7y",
  applications: [
    {
      _id: {
        $oid: "661b1f0f00d5d86b386072ff",
      },
      companyName: "Stevens",
      jobPosition: "Web Developer",
      appCity: "Hoboken",
      appState: "NJ",
      date: "03/01/24",
      followUpDate: "03/22/24",
      appResume: "{}",
      status: "Saved",
      Notes: [
        {
          _id: {
            $oid: "661b1f0f00d5d86b38607300",
          },
          date: "03/14/24",
          time: "4:00pm",
          text: "Asked for an interview on 3/19/24",
        },
      ],
    },
    {
      _id: {
        $oid: "661b1f0f00d5d86b38607301",
      },
      companyName: "TechCorp",
      jobPosition: "Software Engineer",
      appCity: "New York",
      appState: "NY",
      date: "03/05/24",
      followUpDate: "03/25/24",
      appResume: {},
      status: "Screening",
      Notes: [
        {
          _id: {
            $oid: "661b1f0f00d5d86b38607302",
          },
          date: "03/18/24",
          time: "10:00am",
          text: "Received confirmation email for application",
        },
      ],
    },
    {
      _id: {
        $oid: "661b1f0f00d5d86b38607303",
      },
      companyName: "CodeMaster",
      jobPosition: "Frontend Developer",
      appCity: "San Francisco",
      appState: "CA",
      date: "04/01/24",
      followUpDate: "04/15/24",
      appResume: {},
      status: "Hired",
      Notes: [
        {
          _id: {
            $oid: "661b1f0f00d5d86b38607304",
          },
          date: "04/10/24",
          time: "2:30pm",
          text: "Scheduled phone interview for next week",
        },
      ],
    },
    {
      _id: {
        $oid: "661b2fc86e4224fe0e298447",
      },
      companyName: "CodeMaster",
      jobPosition: "Backend Developer",
      appCity: "Los Angeles",
      appState: "CA",
      date: "03/15/24",
      followUpDate: "03/31/24",
      appResume: {},
      status: "Rejected",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b301947fc00384f75e0f8",
      },
      companyName: "DataTech",
      jobPosition: "Data Analyst",
      appCity: "Chicago",
      appState: "IL",
      date: "03/20/24",
      followUpDate: "04/05/24",
      appResume: {},
      status: "Saved",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30391bf05600f19e7730",
      },
      companyName: "CreativeSolutions",
      jobPosition: "UX Designer",
      appCity: "Seattle",
      appState: "WA",
      date: "03/25/24",
      followUpDate: "04/10/24",
      appResume: {},
      status: "Hired",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b3077dd3ce693ff9c9ea2",
      },
      companyName: "FutureVision",
      jobPosition: "Machine Learning Engineer",
      appCity: "Boston",
      appState: "MA",
      date: "04/05/24",
      followUpDate: "04/20/24",
      appResume: {},
      status: "Rejected",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b3093efd4ae5ceb1b731c",
      },
      companyName: "DesignWorks",
      jobPosition: "Graphic Designer",
      appCity: "Portland",
      appState: "OR",
      date: "04/10/24",
      followUpDate: "04/25/24",
      appResume: {},
      status: "Screening",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30a8c67cd16393fb1589",
      },
      companyName: "InnovativeSolutions",
      jobPosition: "Product Manager",
      appCity: "Denver",
      appState: "CO",
      date: "04/15/24",
      followUpDate: "04/30/24",
      appResume: {},
      status: "Applied",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30cb987122f42945d943",
      },
      companyName: "TechCorp",
      jobPosition: "Software Engineer",
      appCity: "New York",
      appState: "NY",
      date: "03/05/24",
      followUpDate: "03/25/24",
      appResume: {},
      status: "Saved",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30cb987122f42945d944",
      },
      companyName: "Amazon",
      jobPosition: "Data Scientist",
      appCity: "San Francisco",
      appState: "CA",
      date: "04/20/24",
      followUpDate: "05/05/24",
      appResume: {},
      status: "Applied",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30cb987122f42945d945",
      },
      companyName: "Google",
      jobPosition: "AI Research Scientist",
      appCity: "Mountain View",
      appState: "CA",
      date: "04/25/24",
      followUpDate: "05/10/24",
      appResume: {},
      status: "Saved",
      Notes: [],
    },
  ],
};

export const user2 = {
  firstName: "Alice",
  lastName: "Johnson",
  city: "Austin",
  state: "TX",
  desiredPosition: "Data Engineer",
  dreamJob: "Microsoft",
  email: "alice.johnson@example.com",
  password: "$2b$16$w5bp8z8MLbSxGNmigT9.W.Z4J8.NMVtuHu/wOmYbFVgpyJsc9z5y2",
  applications: [
    {
      _id: {
        $oid: "661b1f0f00d5d86b386072ff",
      },
      companyName: "TechSolutions",
      jobPosition: "Data Engineer",
      appCity: "Austin",
      appState: "TX",
      date: "05/01/24",
      followUpDate: "05/15/24",
      appResume: {},
      status: "Applied",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b1f0f00d5d86b38607301",
      },
      companyName: "DataTech",
      jobPosition: "Data Scientist",
      appCity: "San Francisco",
      appState: "CA",
      date: "05/05/24",
      followUpDate: "05/20/24",
      appResume: {},
      status: "Saved",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b1f0f00d5d86b38607302",
      },
      companyName: "CloudWorks",
      jobPosition: "Cloud Engineer",
      appCity: "Seattle",
      appState: "WA",
      date: "05/10/24",
      followUpDate: "05/25/24",
      appResume: {},
      status: "Screening",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b2fc86e4224fe0e298447",
      },
      companyName: "DataSolutions",
      jobPosition: "Database Administrator",
      appCity: "New York",
      appState: "NY",
      date: "05/15/24",
      followUpDate: "05/30/24",
      appResume: {},
      status: "Applied",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b301947fc00384f75e0f8",
      },
      companyName: "AI Technologies",
      jobPosition: "AI Researcher",
      appCity: "Boston",
      appState: "MA",
      date: "05/20/24",
      followUpDate: "06/05/24",
      appResume: {},
      status: "Saved",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30391bf05600f19e7730",
      },
      companyName: "SoftwareX",
      jobPosition: "Software Developer",
      appCity: "Chicago",
      appState: "IL",
      date: "05/25/24",
      followUpDate: "06/10/24",
      appResume: {},
      status: "Screening",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b3077dd3ce693ff9c9ea2",
      },
      companyName: "TechGuru",
      jobPosition: "IT Support Specialist",
      appCity: "Houston",
      appState: "TX",
      date: "05/30/24",
      followUpDate: "06/15/24",
      appResume: {},
      status: "Applied",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b3093efd4ae5ceb1b731c",
      },
      companyName: "WebWorks",
      jobPosition: "Web Developer",
      appCity: "Portland",
      appState: "OR",
      date: "06/01/24",
      followUpDate: "06/16/24",
      appResume: {},
      status: "Saved",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30a8c67cd16393fb1589",
      },
      companyName: "DesignTech",
      jobPosition: "UI Designer",
      appCity: "Los Angeles",
      appState: "CA",
      date: "06/05/24",
      followUpDate: "06/20/24",
      appResume: {},
      status: "Screening",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30cb987122f42945d943",
      },
      companyName: "FutureWorks",
      jobPosition: "Future Technologist",
      appCity: "San Francisco",
      appState: "CA",
      date: "06/10/24",
      followUpDate: "06/25/24",
      appResume: {},
      status: "Applied",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30cb987122f42945d944",
      },
      companyName: "InnovateTech",
      jobPosition: "Innovation Manager",
      appCity: "Seattle",
      appState: "WA",
      date: "06/15/24",
      followUpDate: "06/30/24",
      appResume: {},
      status: "Saved",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30cb987122f42945d945",
      },
      companyName: "TechSolutions",
      jobPosition: "Data Engineer",
      appCity: "Austin",
      appState: "TX",
      date: "06/20/24",
      followUpDate: "07/05/24",
      appResume: {},
      status: "Screening",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30cb987122f42945d946",
      },
      companyName: "DataTech",
      jobPosition: "Data Scientist",
      appCity: "San Francisco",
      appState: "CA",
      date: "06/25/24",
      followUpDate: "07/10/24",
      appResume: {},
      status: "Applied",
      Notes: [],
    },
  ],
};

export const user3 = {
  firstName: "Emily",
  lastName: "Johnson",
  city: "Austin",
  state: "TX",
  desiredPosition: "Marketing Manager",
  dreamJob: "Facebook",
  email: "emilyjohnson87@gmail.com",
  password: "$2b$16$2wX7S8qj6T2KqF./wSgML.djt8X01PRevoVbKViBksw.R33q6822i",
  applications: [
    {
      _id: {
        $oid: "661b1f0f00d5d86b386072ff",
      },
      companyName: "Facebook",
      jobPosition: "Marketing Manager",
      appCity: "Menlo Park",
      appState: "CA",
      date: "05/01/24",
      followUpDate: "05/15/24",
      appResume: {},
      status: "Applied",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b1f0f00d5d86b38607301",
      },
      companyName: "Apple",
      jobPosition: "Product Designer",
      appCity: "Cupertino",
      appState: "CA",
      date: "05/05/24",
      followUpDate: "05/20/24",
      appResume: {},
      status: "Saved",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b1f0f00d5d86b38607302",
      },
      companyName: "Netflix",
      jobPosition: "Content Strategist",
      appCity: "Los Gatos",
      appState: "CA",
      date: "05/10/24",
      followUpDate: "05/25/24",
      appResume: {},
      status: "Screening",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b2fc86e4224fe0e298447",
      },
      companyName: "Uber",
      jobPosition: "Product Manager",
      appCity: "San Francisco",
      appState: "CA",
      date: "05/15/24",
      followUpDate: "05/30/24",
      appResume: {},
      status: "Applied",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b301947fc00384f75e0f8",
      },
      companyName: "Tesla",
      jobPosition: "Software Engineer",
      appCity: "Palo Alto",
      appState: "CA",
      date: "05/20/24",
      followUpDate: "06/05/24",
      appResume: {},
      status: "Saved",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30391bf05600f19e7730",
      },
      companyName: "Amazon",
      jobPosition: "Business Analyst",
      appCity: "Seattle",
      appState: "WA",
      date: "05/25/24",
      followUpDate: "06/10/24",
      appResume: {},
      status: "Applied",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b3077dd3ce693ff9c9ea2",
      },
      companyName: "Microsoft",
      jobPosition: "Data Scientist",
      appCity: "Redmond",
      appState: "WA",
      date: "05/30/24",
      followUpDate: "06/15/24",
      appResume: {},
      status: "Saved",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b3093efd4ae5ceb1b731c",
      },
      companyName: "Google",
      jobPosition: "Software Engineer",
      appCity: "Mountain View",
      appState: "CA",
      date: "06/05/24",
      followUpDate: "06/20/24",
      appResume: {},
      status: "Applied",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30a8c67cd16393fb1589",
      },
      companyName: "Airbnb",
      jobPosition: "UX Designer",
      appCity: "San Francisco",
      appState: "CA",
      date: "06/10/24",
      followUpDate: "06/25/24",
      appResume: {},
      status: "Saved",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30cb987122f42945d943",
      },
      companyName: "LinkedIn",
      jobPosition: "Product Manager",
      appCity: "Sunnyvale",
      appState: "CA",
      date: "06/15/24",
      followUpDate: "06/30/24",
      appResume: {},
      status: "Applied",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30cb987122f42945d944",
      },
      companyName: "Twitter",
      jobPosition: "Social Media Manager",
      appCity: "San Francisco",
      appState: "CA",
      date: "06/20/24",
      followUpDate: "07/05/24",
      appResume: {},
      status: "Screening",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30cb987122f42945d945",
      },
      companyName: "Adobe",
      jobPosition: "Graphic Designer",
      appCity: "San Jose",
      appState: "CA",
      date: "06/25/24",
      followUpDate: "07/10/24",
      appResume: {},
      status: "Applied",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30cb987122f42945d946",
      },
      companyName: "Salesforce",
      jobPosition: "Sales Representative",
      appCity: "San Francisco",
      appState: "CA",
      date: "07/01/24",
      followUpDate: "07/15/24",
      appResume: {},
      status: "Saved",
      Notes: [],
    },
  ],
};

export const user4 = {
  firstName: "Michael",
  lastName: "Brown",
  city: "Chicago",
  state: "IL",
  desiredPosition: "Software Developer",
  dreamJob: "Microsoft",
  email: "michaelbrown@example.com",
  password: "$2b$16$QQSFo2IPFUdAx2p28DSEE.bFlKLn1rcjkVTz909EWHSH0LznUAknS",
  applications: [
    {
      _id: {
        $oid: "661b1f0f00d5d86b386072ff",
      },
      companyName: "Microsoft",
      jobPosition: "Software Developer",
      appCity: "Redmond",
      appState: "WA",
      date: "06/01/24",
      followUpDate: "06/15/24",
      appResume: {},
      status: "Applied",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b1f0f00d5d86b38607301",
      },
      companyName: "Google",
      jobPosition: "Product Manager",
      appCity: "Mountain View",
      appState: "CA",
      date: "06/05/24",
      followUpDate: "06/20/24",
      appResume: {},
      status: "Saved",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b1f0f00d5d86b38607302",
      },
      companyName: "Amazon",
      jobPosition: "Data Scientist",
      appCity: "Seattle",
      appState: "WA",
      date: "06/10/24",
      followUpDate: "06/25/24",
      appResume: {},
      status: "Screening",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b2fc86e4224fe0e298447",
      },
      companyName: "Apple",
      jobPosition: "iOS Developer",
      appCity: "Cupertino",
      appState: "CA",
      date: "06/15/24",
      followUpDate: "06/30/24",
      appResume: {},
      status: "Applied",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b301947fc00384f75e0f8",
      },
      companyName: "Facebook",
      jobPosition: "Social Media Manager",
      appCity: "Menlo Park",
      appState: "CA",
      date: "06/20/24",
      followUpDate: "07/05/24",
      appResume: {},
      status: "Saved",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30391bf05600f19e7730",
      },
      companyName: "Tesla",
      jobPosition: "Electrical Engineer",
      appCity: "Palo Alto",
      appState: "CA",
      date: "06/25/24",
      followUpDate: "07/10/24",
      appResume: {},
      status: "Applied",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b3077dd3ce693ff9c9ea2",
      },
      companyName: "Twitter",
      jobPosition: "Software Engineer",
      appCity: "San Francisco",
      appState: "CA",
      date: "07/01/24",
      followUpDate: "07/15/24",
      appResume: {},
      status: "Screening",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b3093efd4ae5ceb1b731c",
      },
      companyName: "Uber",
      jobPosition: "Product Manager",
      appCity: "San Francisco",
      appState: "CA",
      date: "07/05/24",
      followUpDate: "07/20/24",
      appResume: {},
      status: "Saved",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30a8c67cd16393fb1589",
      },
      companyName: "LinkedIn",
      jobPosition: "HR Specialist",
      appCity: "Sunnyvale",
      appState: "CA",
      date: "07/10/24",
      followUpDate: "07/25/24",
      appResume: {},
      status: "Applied",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30cb987122f42945d943",
      },
      companyName: "Salesforce",
      jobPosition: "Sales Representative",
      appCity: "San Francisco",
      appState: "CA",
      date: "07/15/24",
      followUpDate: "07/30/24",
      appResume: {},
      status: "Saved",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30cb987122f42945d944",
      },
      companyName: "Adobe",
      jobPosition: "UI/UX Designer",
      appCity: "San Jose",
      appState: "CA",
      date: "07/20/24",
      followUpDate: "08/05/24",
      appResume: {},
      status: "Applied",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30cb987122f42945d945",
      },
      companyName: "IBM",
      jobPosition: "Systems Analyst",
      appCity: "Armonk",
      appState: "NY",
      date: "07/25/24",
      followUpDate: "08/10/24",
      appResume: {},
      status: "Screening",
      Notes: [],
    },
  ],
};

export const user5 = {
  firstName: "Olivia",
  lastName: "Martinez",
  city: "Los Angeles",
  state: "CA",
  desiredPosition: "Project Manager",
  dreamJob: "Apple",
  email: "oliviamartinez@example.com",
  password: "$2b$16$khfZAAbcm6tMdXXsUYy4p.iQ0uR6g.dRV9qhUnnwxWKrF2YNvKaT2",
  applications: [
    {
      _id: {
        $oid: "661b1f0f00d5d86b386072ff",
      },
      companyName: "Apple",
      jobPosition: "Project Manager",
      appCity: "Cupertino",
      appState: "CA",
      date: "08/01/24",
      followUpDate: "08/15/24",
      appResume: {},
      status: "Applied",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b1f0f00d5d86b38607301",
      },
      companyName: "Google",
      jobPosition: "Software Engineer",
      appCity: "Mountain View",
      appState: "CA",
      date: "08/05/24",
      followUpDate: "08/20/24",
      appResume: {},
      status: "Saved",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b1f0f00d5d86b38607302",
      },
      companyName: "Facebook",
      jobPosition: "Marketing Manager",
      appCity: "Menlo Park",
      appState: "CA",
      date: "08/10/24",
      followUpDate: "08/25/24",
      appResume: {},
      status: "Screening",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b2fc86e4224fe0e298447",
      },
      companyName: "Amazon",
      jobPosition: "Data Scientist",
      appCity: "Seattle",
      appState: "WA",
      date: "08/15/24",
      followUpDate: "08/30/24",
      appResume: {},
      status: "Applied",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b301947fc00384f75e0f8",
      },
      companyName: "Microsoft",
      jobPosition: "Software Developer",
      appCity: "Redmond",
      appState: "WA",
      date: "08/20/24",
      followUpDate: "09/05/24",
      appResume: {},
      status: "Saved",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30391bf05600f19e7730",
      },
      companyName: "Netflix",
      jobPosition: "Content Strategist",
      appCity: "Los Gatos",
      appState: "CA",
      date: "08/25/24",
      followUpDate: "09/10/24",
      appResume: {},
      status: "Applied",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b3077dd3ce693ff9c9ea2",
      },
      companyName: "Uber",
      jobPosition: "Product Manager",
      appCity: "San Francisco",
      appState: "CA",
      date: "09/01/24",
      followUpDate: "09/15/24",
      appResume: {},
      status: "Screening",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b3093efd4ae5ceb1b731c",
      },
      companyName: "Tesla",
      jobPosition: "Electrical Engineer",
      appCity: "Palo Alto",
      appState: "CA",
      date: "09/05/24",
      followUpDate: "09/20/24",
      appResume: {},
      status: "Applied",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30a8c67cd16393fb1589",
      },
      companyName: "LinkedIn",
      jobPosition: "HR Specialist",
      appCity: "Sunnyvale",
      appState: "CA",
      date: "09/10/24",
      followUpDate: "09/25/24",
      appResume: {},
      status: "Saved",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30cb987122f42945d943",
      },
      companyName: "Salesforce",
      jobPosition: "Sales Representative",
      appCity: "San Francisco",
      appState: "CA",
      date: "09/15/24",
      followUpDate: "09/30/24",
      appResume: {},
      status: "Applied",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30cb987122f42945d944",
      },
      companyName: "Adobe",
      jobPosition: "UI/UX Designer",
      appCity: "San Jose",
      appState: "CA",
      date: "09/20/24",
      followUpDate: "10/05/24",
      appResume: {},
      status: "Saved",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30cb987122f42945d945",
      },
      companyName: "IBM",
      jobPosition: "Systems Analyst",
      appCity: "Armonk",
      appState: "NY",
      date: "09/25/24",
      followUpDate: "10/10/24",
      appResume: {},
      status: "Screening",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30cb987122f42945d946",
      },
      companyName: "Twitter",
      jobPosition: "Software Engineer",
      appCity: "San Francisco",
      appState: "CA",
      date: "09/30/24",
      followUpDate: "10/15/24",
      appResume: {},
      status: "Applied",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30cb987122f42945d947",
      },
      companyName: "LinkedIn",
      jobPosition: "Product Manager",
      appCity: "Sunnyvale",
      appState: "CA",
      date: "10/05/24",
      followUpDate: "10/20/24",
      appResume: {},
      status: "Saved",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30cb987122f42945d948",
      },
      companyName: "Microsoft",
      jobPosition: "Data Scientist",
      appCity: "Redmond",
      appState: "WA",
      date: "10/10/24",
      followUpDate: "10/25/24",
      appResume: {},
      status: "Applied",
      Notes: [],
    },
    {
      _id: {
        $oid: "661b30cb987122f42945d949",
      },
      companyName: "Amazon",
      jobPosition: "Software Engineer",
      appCity: "Seattle",
      appState: "WA",
      date: "10/15/24",
      followUpDate: "10/30/24",
      appResume: {},
      status: "Screening",
      Notes: [],
    },
  ],
};


